name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  api_calls:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate and use Bearer Token
        run: |
          # 1. Auth
          TOKEN=$(curl -X POST \
            'https://cloud.uipath.com/identity_/connect/authorize' \
            -d "grant_type=client_credentials&client_id=b43421b2-ef24-4119-b474-8547e4aed701&client_secret=9zNFRO!fv#PH3J#S&scope0OR.Queues" | jq -r '.access_token')


          echo "Received token: $TOKEN"

          # 2. Add queue item
          curl -X POST \
            'https://uipath.desa.portal.ss/odata/Queues/UiPathODataSvc.AddQueueItem' \
            -H 'accept: application/json' \
            -H 'X-UIPATH-OrganizationUnitId: 1' \
            -H 'authorization: Bearer $TOKEN' \
            -H 'Content-Type: application/json;odata.metadata=minimal;odata.streaming=true' \
            -d '{
            "itemData": {
              "Name": "devopts",
              "Priority": "Normal",
              "Reference": "Process_name",
              "SpecificContent": {
                "url_repo": "https://github.com/organization/Uipath_devopts.git"
              }
            }
          }'
