name: CI Uipath

on:
  push:
    branches:
      - main

jobs:
  api_calls:
    runs-on: ubuntu-latest
    steps:
      - name: Auth
        run: |
          TOKEN=$(curl -X POST \
            'https://cloud.uipath.com/testgqdkglt/identity_/connect/token' \
            -H 'Content-Type: application/x-www-form-urlencoded' \
            -d "grant_type=client_credentials&client_id=b43421b2-ef24-4119-b474-8547e4aed701&client_secret=9zNFRO!fv#PH3J#S&scope=OR.Queues" \
            | jq -r '.access_token')
          echo "TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: addQueue
        run: |
          curl -X POST \
            'https://cloud.uipath.com/testgqdkglt/DefaultTenant/orchestrator_/odata/Queues/UiPathODataSvc.AddQueueItem' \
            -H 'accept: application/json' \
            -H 'X-UIPATH-OrganizationUnitId: 275862' \
            -H "authorization: Bearer $TOKEN" \
            -H 'Content-Type: application/json;odata.metadata=minimal;odata.streaming=true' \
            -d '{
            "itemData": {
              "Name": "devopts",
              "Priority": "Normal",
              "Reference": "Process_name",
              "SpecificContent": {
                "url_repo": "https://github.com/organization/Uipath_devopts.git"
              }
            }
          }'
